### ISSUE TITLE
스키장 현황(image talk) 업로드 기능.

### ISSUE THREAD

**Issue by joel-jo-querypie** [g1moon/hello-waterski#7]
현재 modal 식으로 ui만 들어둔 상태.
- [x] 사진과 함께 업로드하는 기능 추가 필요함.
- [x] image 를 올리는 부분을 input으로 만들어 두었는데, 이미지 업로더로 변경 필요함.
- [ ] 이미지 클릭을 하면 백그라운드가 검은색인데 opacity를 조정 할 필요 있음.

**Comment by g1moon** [comment]
이미지 업로드 시 미리보기 추가
